ArticleSearch.Web/Controllers/ElectricalController.cs
using ArticleSearch.Service;
using ArticleSearch.Service.ImportData;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ArticleSearch.Service.ArticleServices;
using ArticleSearch.Data;
using Models;
using ArticleSearch.Service.ProductFamilyServices;
using ArticleSearch.Service.ProductFamilyDimensionMappingServices;

using Models;
using System.Xml.Linq;
using ArticleSearch.Model;
using System.Collections;

using System.Collections;
using ArticleSearch.Web.Models;

namespace ArticleSearch.Web.Controllers
{
    public class ElectricalController : Controller
    {
        //
        // GET: /Electrical/
        #region Decl
        private readonly IImportDataService _importDataService;
        private readonly IArticleService _articleService;
        private readonly IProductFamilyService _productFamilyService;
        private readonly IProductFamilyDimensionMappingService _productFamilyDimensionMappingService;
        #endregion

        #region Ctro
        public ElectricalController(IImportDataService importDataService, IArticleService articleService, IProductFamilyService productFamilyService, IProductFamilyDimensionMappingService productFamilyDimensionMappingService)
        {
            _importDataService = importDataService;
            _articleService = articleService;
            _productFamilyService = productFamilyService;
            _productFamilyDimensionMappingService = productFamilyDimensionMappingService;
        }

#endregion

        #region method
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Rotating()
        {
            return View();
        }
        public ActionResult Asynchronous()
        {
            return View();
        }
        public ActionResult Slip_ring()
        {
            return View();
        }
        public ActionResult Article_Info()
        {
            return View();
        }
        public ActionResult Family_List()
        {
            return View();
        }
        public ActionResult Family_Fig()
        {
            return View();
        }
        public ActionResult Search_Form()
        {
            return View();
        }


       
        [HttpPost]
        public JsonResult SearchForm_byParameters(ArticleSearchParameters searchParameters)
        {
            //ArticleSearchParameters searchParameters = new ArticleSearchParameters();
            //searchParameters.ArticleNo = articleNo; //"1089 9284 01";
            //searchParameters.FamilyNo = familyNo;  //"0983 2460 00";
            //searchParameters.ArticleName = articleName; //"CAPACITOR";
            //searchParameters.SG = SG; //1;
            //searchParameters.SC = SC;  //"1;1;2";
            //searchParameters.TechnicalData = TechnicalData; //"± 20 %";// "10000 µF";
            //searchParameters.supplyerName = supplyerName;//"";
            //searchParameters.supplyerDesignation = supplyerDesignation; //"";

            //test
            List<ArticleMetadata> FilteredArticles = (from p in _articleService.GetAll()
                                   group p by p.ProductFamily.FamilyNumber into g
                                    select new ArticleMetadata
                                    {
                                        
                                        ProductFamilyNo = g.Key,

                                        ArticleData = g.ToList().Select(a => new ArticleData
                                        {
                                            Id = a.Id,
                                            ArticleNo = a.ArticleNo,
                                            ArticleName = a.ArticleName,
                                            ProductFamilyId = a.ProductFamilyId,
                                            ProductFamilyNo = a.ProductFamily.FamilyNumber,
                                            ProductFamilName = a.ProductFamily.FamilyName,
                                            DrawingNo = a.DrawingNo,
                                            SC = a.SC,
                                            SG = a.SG,
                                            SupplierName = a.Supplier.Name,
                                            SupplierDesignation = a.Supplier.Designation,
                                            UsedAt = a.UsedAt,
                                            ArticleXMLdata = a.ArticleDimensonData                                        
                                        }).ToList()
                                    }).ToList();

             

            //ends

            //List<ArticleData> FilteredArticles = new List<global::Models.ArticleData>();
            //var All_articleData = _articleService.GetAll().Select(a => new ArticleData
            //{
            //    Id = a.Id,
            //    ArticleNo = a.ArticleNo,
            //    ArticleName = a.ArticleName,
            //    ProductFamilyId = a.ProductFamilyId,
            //    ProductFamilyNo = a.ProductFamily.FamilyNumber,
            //    ProductFamilName = a.ProductFamily.FamilyName,
            //    DrawingNo = a.DrawingNo,
            //    SC = a.SC,
            //    SG = a.SG,
            //    SupplierName = a.Supplier.Name,
            //    SupplierDesignation = a.Supplier.Designation,
            //    UsedAt = a.UsedAt,
            //    ArticleXMLdata = a.ArticleDimensonData
            //}).ToList();

            //FilteredArticles = All_articleData;
//serverside filter commented here
            //if (searchParameters.ArticleNo != "")
            //{
                
            //    FilteredArticles = FilteredArticles.Where(x => x.ArticleData[0].ArticleNo.Equals(searchParameters.ArticleNo)).ToList();
            //    if (FilteredArticles.Count == 0)
            //    {
            //        ViewBag.Data = null;
            //        return null;//View();
            //    }
               
            //}
            //if (searchParameters.FamilyNo != "")
            //{
            //    FilteredArticles = FilteredArticles.Where(x => x.ProductFamilyNo.Equals(searchParameters.FamilyNo)).ToList();
            //    if (FilteredArticles.Count == 0)
            //    {
            //        ViewBag.Data = null;
            //        return null;//View();
            //    }
            //}
            //if (searchParameters.ArticleName != "")
            //{
            //    FilteredArticles = FilteredArticles.Where(x => x.ArticleData[0].ArticleName.Equals(searchParameters.ArticleName)).ToList();
            //    if (FilteredArticles.Count == 0)
            //    {
            //        ViewBag.Data = null;
            //        return null;//View();
            //    }
            //}
            //if (searchParameters.SG != 0)
            //{
            //    FilteredArticles = FilteredArticles.Where(x =>x.SG.Equals(searchParameters.SG)).ToList();
            //    if (FilteredArticles.Count == 0)
            //    {
            //        ViewBag.Data = null;
            //        return null;//View();
            //    }
            //}
            //if (searchParameters.SC != "")
            //{
            //    FilteredArticles = FilteredArticles.Where(x => x.SC.Equals(searchParameters.SC)).ToList();
            //    if (FilteredArticles.Count == 0)
            //    {
            //        ViewBag.Data = null;
            //        return null;//View();
            //    }
            //}
            //if (searchParameters.SpecificComppanyDesignation != "" && searchParameters.SpecificComppanyDesignation != null)
            //{
            //    FilteredArticles = FilteredArticles.Where(x => x.SpecificCompany.Equals(searchParameters.SpecificComppanyDesignation)).ToList();
            //    if (FilteredArticles.Count == 0)
            //    {
            //        ViewBag.Data = null;
            //        return null;//View();
            //    }
            //}
            //if (searchParameters.TechnicalData != "")
            //{
            //    FilteredArticles = FilteredArticles.Where(x => x.ArticleXMLdata.Contains(searchParameters.TechnicalData)).ToList();
            //    if (FilteredArticles.Count == 0)
            //    {
            //        ViewBag.Data = null;
            //        return null;//View();
            //    }
            //}
            //if (searchParameters.supplyerName != "")
            //{
            //    FilteredArticles = FilteredArticles.Where(x => x.SupplierName.Contains(searchParameters.supplyerName)).ToList();
            //    if (FilteredArticles.Count == 0)
            //    {
            //        ViewBag.Data = null;
            //        return null;//View();
            //    }
            //}
            //if (searchParameters.supplyerDesignation != "")
            //{
            //    FilteredArticles = FilteredArticles.Where(x => x.SupplierDesignation.Contains(searchParameters.supplyerDesignation)).ToList();
            //    if (FilteredArticles.Count == 0)
            //    {
            //        ViewBag.Data = null;
            //        return null;//View();
            //    }
            //}
            //int i = 0;
            try
            {
                foreach (var item in FilteredArticles)
                {
                    for (int i = 0; i < item.ArticleData.Count; i++)
                    {
                        item.ArticleData[i].ArticleDimensonData = xmlToList(item.ArticleData[i].ArticleXMLdata);
                        item.ArticleData[i].ArticleDimensonColoms = _productFamilyDimensionMappingService.GetAll().Where(x => x.ProductFamilyId.Equals(item.ArticleData[0].ProductFamilyId)).Select(a => a.Dimension.Name).Distinct();  //get all meta data cols of current family; //familyDimColoms(item.ProductFamilyId);    
                    }

ArticleSearch.Web/Views/Electrical/Asynchronous.cshtml
@{
    ViewBag.Title = "Asynchronous";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row sm-padding-bottom border-bottom fifth-border-color">
    <div class="col-lg-12 col-sm-12">
        <div class="col-lg-12 col-sm-12">
            <div><span class="first-color">Index Level &nbsp:</span><a href="/Electrical/Index" class="xs-padding-right first-color"> 1 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Electrical/Rotating" class="xs-padding-right first-color"> 1.01 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><span> 1.01.01 </span></div>
            <div><span class="first-color">Index Name : </span><span>Asynchronous motors, 3-phase, ventilated, enclosed - Asynkronmotorer, 3-fas, ventilerade, kapslade </span></div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row md-margin-top-bottom">
        <div class="col-lg-12 col-sm-12">
            <div class="btn-group">
                <a href="@Url.Action("Index", "Electrical")" class="btn fifth-border-color first-bg-color fifth-color">Search Index</a>
                <a href="@Url.Action("Search_Form", "Electrical")" class="btn fifth-border-color first-bg-color fifth-color">Search Form</a>
            </div>
        </div>
        <div class="row">
            <div class=" col-sm-12 sm-margin-top-bottom">
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="@Url.Action("Slip_ring", "Electrical")" title="Slip ring motors - foot-mounted">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Slip ring motors - foot-mounted
                                <span class="badge float-right fifth-bg-color first-color">1</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/Index3/0.gif" />
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="#" title="Slip ring motors - flange mounted">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Slip ring motors - flange mounted
                                <span class="badge float-right fifth-bg-color first-color">2</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/Index3/1.gif" />
                                <img src="/Content/images/Index3/2.gif" />
                                <img src="/Content/images/Index3/3.gif" />
                                <img src="/Content/images/Index3/4.gif" />
                            </div>
                        </a>
                    </div>

                </div>
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="#" title="Slip ring motors - foot- and flange mounted">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Slip ring motors - foot- and flange mounted
                                <span class="badge float-right fifth-bg-color first-color">3</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/Index3/5.gif" />
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 sm-margin-top-bottom">
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="#" title="Squirrel cage motors - foot-mounted">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Squirrel cage motors - foot-mounted
                                <span class="badge float-right fifth-bg-color first-color">4</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/Index3/6.gif" />
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="#" title="Squirrel cage motors - flange mounted">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Squirrel cage motors - flange mounted
                                <span class="badge float-right fifth-bg-color first-color">5</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/Index3/7.gif" />
                                <img src="/Content/images/Index3/8.gif" />
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="#" title="Squirrel cage motors - foot- and flange mounted">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Squirrel cage motors - foot- and flange mounted
                                <span class="badge float-right fifth-bg-color first-color">6</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/Index3/9.gif" />
                                <img src="/Content/images/Index3/10.gif" />
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>

ArticleSearch.Web/Views/Electrical/Family_Fig.cshtml
@{
    ViewBag.Title = "Family_Fig";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row sm-padding-bottom border-bottom fifth-border-color">
    <div class="col-lg-12 col-sm-12">
        <div class="col-lg-12 col-sm-12">
            <div><a href="/Home/Index" class="xs-padding-right first-color"> Home </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Electrical/Index" class="xs-padding-right first-color"> 1 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Electrical/Rotating" class="xs-padding-right first-color"> 1.01 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Electrical/Asynchronous" class="xs-padding-right first-color"> 1.01.01 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Electrical/Slip_ring" class="xs-padding-right first-color"> 1.01.01.01 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><span>Family Figures</span></div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row md-margin-top-bottom">
        <div class="col-sm-12">
            <div class="btn-group">
                <a href="@Url.Action("Index", "Electrical")" class="btn fifth-border-color first-bg-color fifth-color">Search Index</a>
                <a href="@Url.Action("Search_Form", "Electrical")" class="btn fifth-border-color first-bg-color fifth-color">Search Form</a>
                <a href="#" class="btn fifth-border-color first-bg-color fifth-color" data-toggle="modal" data-target="#myModal">Create</a>
                <div class="btn-group">
                    <a href="#" class="btn fifth-border-color first-bg-color fifth-color dropdown-toggle" data-toggle="dropdown">
                        View &nbsp<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="@Url.Action("Family_Fig", "Electrical")">Family Figures</a></li>
                        <li><a href="#">Family Description</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="row md-margin-top-bottom">
        <div class="col-sm-12">
            <div class="md-text md-margin-top-bottom"><b>Family No. : </b> 0101 1100 00</div>
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading fourth-bg-color">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
                                Type A2S. Unhardened parallel pin with chamfered/spherical ends.
                            </a>
                        </h4>
                    </div>
                    <div id="collapse1" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <img src="/Content/images/Index2/0.gif" />                            
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading fourth-bg-color">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
                                Type A2. Unhardened parallel pin with chamfered ends.
                            </a>
                        </h4>
                    </div>
                    <div id="collapse2" class="panel-collapse collapse">
                        <div class="panel-body">
                            <img src="/Content/images/Index2/1.gif" />                            
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading fourth-bg-color">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
                                Type A3. Unhardened parallel pin with chamfered and pushed in ends, the so called ”Marcus pin”.
                            </a>
                        </h4>
                    </div>
                    <div id="collapse3" class="panel-collapse collapse">
                        <div class="panel-body">
                            <img src="/Content/images/Index2/2.gif" />
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header first-bg-color fifth-color">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Create</h4>
            </div>
            <div class="modal-body text-center first-color md-margin-top-bottom">
                <h1 class="bold">Coming Soon</h1>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn first-bg-color fifth-color" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

ArticleSearch.Web/Views/Electrical/Family_List.cshtml
@{
    ViewBag.Title = "Search_Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row sm-padding-bottom border-bottom fifth-border-color">
    <div class="col-lg-12 col-sm-12">
        <div class="col-lg-12 col-sm-12">
            <div><a href="/Home/Index" class="xs-padding-right first-color"> Home </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Electrical/Index" class="xs-padding-right first-color"> 1 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Electrical/Rotating" class="xs-padding-right first-color"> 1.01 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Electrical/Asynchronous" class="xs-padding-right first-color"> 1.01.01 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Electrical/Slip_ring" class="xs-padding-right first-color"> 1.01.01.01 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><span>Family_List</span></div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row md-margin-top-bottom">
        <div class="col-sm-12">
            <div class="btn-group">
                <a href="@Url.Action("Index", "Electrical")" class="btn fifth-border-color first-bg-color fifth-color">Search Index</a>
                <a href="@Url.Action("Search_Form", "Electrical")" class="btn fifth-border-color first-bg-color fifth-color">Search Form</a>
                <a href="#" class="btn fifth-border-color first-bg-color fifth-color" data-toggle="modal" data-target="#myModal">Create</a>
                <div class="btn-group">
                    <a href="#" class="btn fifth-border-color first-bg-color fifth-color dropdown-toggle" data-toggle="dropdown">
                        View &nbsp<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="@Url.Action("Family_Fig", "Electrical")">Family Figures</a></li>
                        <li><a href="#">Family Description</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="row md-margin-top-bottom">
        <div class="col-sm-12">
            <a href="@Url.Action("Article_Info", "Electrical")">Type A2. Unhardened parallel pin with chamfered ends.</a>
        </div>
    </div>
</div>



<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header first-bg-color fifth-color">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Create</h4>
            </div>
            <div class="modal-body text-center first-color md-margin-top-bottom">
                <h1 class="bold">Coming Soon</h1>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn first-bg-color fifth-color" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

ArticleSearch.Web/Views/Electrical/Slip_ring.cshtml
@{
    ViewBag.Title = "Slip_ring";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row sm-padding-bottom border-bottom fifth-border-color">
    <div class="col-lg-12 col-sm-12">
        <div class="col-lg-12 col-sm-12">
            <div><span class="first-color">Index Level &nbsp:</span><a href="/Electrical/Index" class="xs-padding-right first-color"> 1 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Electrical/Rotating" class="xs-padding-right first-color"> 1.01 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Electrical/Asynchronous" class="xs-padding-right first-color"> 1.01.01 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><span> 1.01.01.01 </span></div>
            <div><span class="first-color">Index Name : </span><span>Slip ring motors - foot-mounted</span></div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row md-margin-top-bottom">
        <div class="col-lg-12 col-sm-12">
            <div class="btn-group">
                <a href="@Url.Action("Index", "Electrical")" class="btn fifth-border-color first-bg-color fifth-color">Search Index</a>
                <a href="@Url.Action("Search_Form", "Electrical")" class="btn fifth-border-color first-bg-color fifth-color">Search Form</a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 sm-margin-top-bottom">
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="@Url.Action("Family_List", "Electrical")" title="Asynchronous motors, 3-phase, ventilated, enclosed - Foot-mounted slip ring motor with metric sized shaft and frame, special types (0971 1112 00)">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Asynchronous motors, 3-phase, ventilated, enclosed - Foot-mounted slip ring motor with metric sized shaft and frame, special types (0971 1112 00)
                                <span class="badge float-right fifth-bg-color first-color">1</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/Index3/0.gif" />
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>