ArticleSearch.Web/Controllers/MechanicalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ArticleSearch.Web.Controllers
{
    public class MechanicalController : Controller
    {
        //
        // GET: /Mechanical/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Fasteners()
        {
            return View();
        }
        public ActionResult Pins()
        {
            return View();
        }

        public ActionResult Parallel_Pins()
        {
            return View();
        }
        public ActionResult Article_Info()
        {
            return View();
        }
        public ActionResult Family_List()
        {
            return View();
        }
        public ActionResult Family_Fig()
        {
            return View();
        }
        public ActionResult Search_Form()
        {
            return View();
        }
    }
}

ArticleSearch.Web/Views/Mechanical/Family_Fig.cshtml
@{
    ViewBag.Title = "Family_Fig";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row sm-padding-bottom border-bottom fifth-border-color">
    <div class="col-lg-12 col-sm-12">
        <div class="col-lg-12 col-sm-12">
            <div><a href="/Home/Index" class="xs-padding-right first-color"> Home </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Electrical/Index" class="xs-padding-right first-color"> 1 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Electrical/Rotating" class="xs-padding-right first-color"> 1.01 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Electrical/Asynchronous" class="xs-padding-right first-color"> 1.01.01 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Electrical/Slip_ring" class="xs-padding-right first-color"> 1.01.01.01 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><span>Family Figures</span></div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row md-margin-top-bottom">
        <div class="col-sm-12">
            <div class="btn-group">
                <a href="@Url.Action("Index", "Mechanical")" class="btn fifth-border-color first-bg-color fifth-color">Search Index</a>
                <a href="@Url.Action("Search_Form", "Mechanical")" class="btn fifth-border-color first-bg-color fifth-color">Search Form</a>
                <a href="#" class="btn fifth-border-color first-bg-color fifth-color" data-toggle="modal" data-target="#myModal">Create</a>
                <div class="btn-group">
                    <a href="#" class="btn fifth-border-color first-bg-color fifth-color dropdown-toggle" data-toggle="dropdown">
                        View &nbsp<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="@Url.Action("Family_Fig", "Mechanical")">Family Figures</a></li>
                        <li><a href="#">Family Description</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="row md-margin-top-bottom">
        <div class="col-sm-12">
            <div class="md-text md-margin-top-bottom"><b>Family No. : </b> 0101 1100 00</div>
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading fourth-bg-color">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
                                Type A2S. Unhardened parallel pin with chamfered/spherical ends.
                            </a>
                        </h4>
                    </div>
                    <div id="collapse1" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <img src="/Content/images/Index2/0.gif" />
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading fourth-bg-color">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
                                Type A2. Unhardened parallel pin with chamfered ends.
                            </a>
                        </h4>
                    </div>
                    <div id="collapse2" class="panel-collapse collapse">
                        <div class="panel-body">
                            <img src="/Content/images/Index2/1.gif" />
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading fourth-bg-color">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
                                Type A3. Unhardened parallel pin with chamfered and pushed in ends, the so called ”Marcus pin”.
                            </a>
                        </h4>
                    </div>
                    <div id="collapse3" class="panel-collapse collapse">
                        <div class="panel-body">
                            <img src="/Content/images/Index2/2.gif" />
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header first-bg-color fifth-color">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Create</h4>
            </div>
            <div class="modal-body text-center first-color md-margin-top-bottom">
                <h1 class="bold">Coming Soon</h1>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn first-bg-color fifth-color" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

ArticleSearch.Web/Views/Mechanical/Family_List.cshtml
@{
    ViewBag.Title = "Search_Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row sm-padding-bottom border-bottom fifth-border-color">
    <div class="col-lg-12 col-sm-12">
        <div class="col-lg-12 col-sm-12">
            <div><a href="/Home/Index" class="xs-padding-right first-color"> Home </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Electrical/Index" class="xs-padding-right first-color"> 1 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Electrical/Rotating" class="xs-padding-right first-color"> 1.01 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Electrical/Asynchronous" class="xs-padding-right first-color"> 1.01.01 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Electrical/Slip_ring" class="xs-padding-right first-color"> 1.01.01.01 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><span>Family List</span></div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row md-margin-top-bottom">
        <div class="col-sm-12">
            <div class="btn-group">
                <a href="@Url.Action("Index", "Mechanical")" class="btn fifth-border-color first-bg-color fifth-color">Search Index</a>
                <a href="@Url.Action("Search_Form", "Mechanical")" class="btn fifth-border-color first-bg-color fifth-color">Search Form</a>
                <a href="#" class="btn fifth-border-color first-bg-color fifth-color" data-toggle="modal" data-target="#myModal">Create</a>
                <div class="btn-group">
                    <a href="#" class="btn fifth-border-color first-bg-color fifth-color dropdown-toggle" data-toggle="dropdown">
                        View &nbsp<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="@Url.Action("Family_Fig", "Mechanical")">Family Figures</a></li>
                        <li><a href="#">Family Description</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="row md-margin-top-bottom">
        <div class="col-sm-12">
            <a href="@Url.Action("Article_Info", "Mechanical")">Type A2. Unhardened parallel pin with chamfered ends.</a>
        </div>
    </div>
</div>



<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header first-bg-color fifth-color">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Create</h4>
            </div>
            <div class="modal-body text-center first-color md-margin-top-bottom">
                <h1 class="bold">Coming Soon</h1>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn first-bg-color fifth-color" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

ArticleSearch.Web/Views/Mechanical/Fasteners.cshtml
@{
    ViewBag.Title = "Fasteners";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row sm-padding-bottom border-bottom fifth-border-color">
    <div class="col-lg-12 col-sm-12">
        <div class="col-lg-12 col-sm-12">
            <div><span class="first-color">Index Level &nbsp:</span><a href="/Mechanical/Index" class="xs-padding-right first-color"> 1 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><span> 1.01 </span></div>
            <div><span class="first-color">Index Name : </span><span>Fasteners - Fästelement</span></div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row md-margin-top-bottom">
        <div class="col-lg-12 col-sm-12">
            <div class="btn-group">
                <a href="@Url.Action("Index", "Mechanical")" class="btn fifth-border-color first-bg-color fifth-color">Search Index</a>
                <a href="@Url.Action("Search_Form", "Mechanical")" class="btn fifth-border-color first-bg-color fifth-color">Search Form</a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 sm-margin-top-bottom">
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="@Url.Action("Pins", "Mechanical")" title="Pins">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Pins
                                <span class="badge float-right fifth-bg-color first-color">1</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/M_Index2/0.gif" />
                                <img src="/Content/images/M_Index2/1.gif" />
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="#" title="Rivets">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Rivets
                                <span class="badge float-right fifth-bg-color first-color">2</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/M_Index2/2.gif" />
                                <img src="/Content/images/M_Index2/3.gif" />
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="#" title="Screws">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Screws
                                <span class="badge float-right fifth-bg-color first-color">3</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/M_Index2/4.gif" />
                                <img src="/Content/images/M_Index2/5.gif" />
                                <img src="/Content/images/M_Index2/6.gif" />
                                <img src="/Content/images/M_Index2/7.gif" />
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 sm-margin-top-bottom">
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="#" title="Thread inserts">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Thread inserts
                                <span class="badge float-right fifth-bg-color first-color">4</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/M_Index2/8.gif" />
                                <img src="/Content/images/M_Index2/9.gif" />
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="#" title="Nuts">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Nuts
                                <span class="badge float-right fifth-bg-color first-color">5</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/M_Index2/10.gif" />
                                <img src="/Content/images/M_Index2/11.gif" />
                                <img src="/Content/images/M_Index2/12.gif" />
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="#" title="Washers">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Washers
                                <span class="badge float-right fifth-bg-color first-color">6</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/M_Index2/13.gif" />
                                <img src="/Content/images/M_Index2/14.gif" />
                                <img src="/Content/images/M_Index2/15.gif" />
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 sm-margin-top-bottom">
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="#" title="Shims, sleeves, spacers and locking dogs">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Shims, sleeves, spacers and locking dogs
                                <span class="badge float-right fifth-bg-color first-color">7</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/M_Index2/16.gif" />
                                <img src="/Content/images/M_Index2/17.gif" />
                                <img src="/Content/images/M_Index2/18.gif" />
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ArticleSearch.Web/Views/Mechanical/Parallel_Pins.cshtml
@{
    ViewBag.Title = "Parallel_Pins";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row sm-padding-bottom border-bottom fifth-border-color">
    <div class="col-lg-12 col-sm-12">
        <div class="col-lg-12 col-sm-12">
            <div><span class="first-color">Index Level &nbsp:</span><a href="/Mechanical/Index" class="xs-padding-right first-color"> 1 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Mechanical/Fasteners" class="xs-padding-right first-color"> 1.01 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Mechanical/Pins" class="xs-padding-right first-color"> 1.01.01 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><span> 1.01.01.01 </span></div>
            <div><span class="first-color">Index Name : </span><span>Parallel pins - Cylindriska pinnar</span></div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row md-margin-top-bottom">
        <div class="col-lg-12 col-sm-12">
            <div class="btn-group">
                <a href="@Url.Action("Index", "Mechanical")" class="btn fifth-border-color first-bg-color fifth-color">Search Index</a>
                <a href="@Url.Action("Search_Form", "Mechanical")" class="btn fifth-border-color first-bg-color fifth-color">Search Form</a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 sm-margin-top-bottom">
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="@Url.Action("Family_List", "Mechanical")" title="Parallel pins, D-tolerance m6 (0101 1100 00)">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Parallel pins, D-tolerance m6 (0101 1100 00)
                                <span class="badge float-right fifth-bg-color first-color">1</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/M_Index4/0.gif" />
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="#" title="Parallel pins, D-tolerance h6, h8, h11, etc. (0102 1100 00)">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Parallel pins, D-tolerance h6, h8, h11, etc. (0102 1100 00)
                                <span class="badge float-right fifth-bg-color first-color">1</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/M_Index4/1.gif" />
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="#" title="Hardened parallel pins with internal M-thread, D-tolerance m6 (0104 0400 00)">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Hardened parallel pins with internal M-thread, D-tolerance m6 (0104 0400 00)
                                <span class="badge float-right fifth-bg-color first-color">1</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/M_Index4/2.gif" />
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 sm-margin-top-bottom">
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="#" title="Bearing Roller (0517 0100 00)">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Bearing Roller (0517 0100 00)
                                <span class="badge float-right fifth-bg-color first-color">1</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/M_Index4/3.gif" />
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ArticleSearch.Web/Views/Mechanical/Pins.cshtml
@{
    ViewBag.Title = "Pins";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row sm-padding-bottom border-bottom fifth-border-color">
    <div class="col-lg-12 col-sm-12">
        <div class="col-lg-12 col-sm-12">
            <div><span class="first-color">Index Level &nbsp:</span><a href="/Electrical/Index" class="xs-padding-right first-color"> 1 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><a href="/Mechanical/Fasteners" class="xs-padding-right first-color"> 1.01 </a><span class="xs-padding-right"><i class="fa fa-angle-right first-color sm-text"></i></span><span> 1.01.01 </span></div>
            <div><span class="first-color">Index Name : </span><span>Pins - Pinnar</span></div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row md-margin-top-bottom">
        <div class="col-lg-12 col-sm-12">
            <div class="btn-group">
                <a href="@Url.Action("Index", "Mechanical")" class="btn fifth-border-color first-bg-color fifth-color">Search Index</a>
                <a href="@Url.Action("Search_Form", "Mechanical")" class="btn fifth-border-color first-bg-color fifth-color">Search Form</a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 sm-margin-top-bottom">
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="@Url.Action("Parallel_Pins", "Mechanical")" title="Parallel pins">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Parallel pins
                                <span class="badge float-right fifth-bg-color first-color">1</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/M_Index2/0.gif" />
                                <img src="/Content/images/M_Index2/1.gif" />
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="#" title="Taper pins">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Taper pins
                                <span class="badge float-right fifth-bg-color first-color">2</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/M_Index2/2.gif" />
                                <img src="/Content/images/M_Index2/3.gif" />
                                <img src="/Content/images/M_Index2/4.gif" />
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="#" title="Grooved pins">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Grooved pins
                                <span class="badge float-right fifth-bg-color first-color">3</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/M_Index2/5.gif" />
                                <img src="/Content/images/M_Index2/6.gif" />
                                <img src="/Content/images/M_Index2/7.gif" />
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 sm-margin-top-bottom">
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="#" title="Spring pins and spiral pins (0108 1000 00)">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Spring pins and spiral pins (0108 1000 00)
                                <span class="badge float-right fifth-bg-color first-color">4</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/M_Index2/8.gif" />
                                <img src="/Content/images/M_Index2/9.gif" />
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="#" title="Split cotter pins, clips and cotters">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Split cotter pins, clips and cotters
                                <span class="badge float-right fifth-bg-color first-color">5</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/M_Index2/10.gif" />
                                <img src="/Content/images/M_Index2/11.gif" />
                                <img src="/Content/images/M_Index2/12.gif" />
                                <img src="/Content/images/M_Index2/13.gif" />
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="panel panel-default first-border-color">
                        <a href="#" title="Clevis pins and parallel pins with hole (0113 2000 00)">
                            <div class="panel-heading btnDataOverflow first-bg-color fifth-color">
                                Clevis pins and parallel pins with hole (0113 2000 00)
                                <span class="badge float-right fifth-bg-color first-color">6</span>
                            </div>
                            <div class="panel-body btnDataImg">
                                <img src="/Content/images/M_Index2/14.gif" />
                                <img src="/Content/images/M_Index2/15.gif" />
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>