ArticleSearch.Web/Controllers/FamilyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ArticleSearch.Web.Models;
using ArticleSearch.Service.ProductFamilyServices;
using ArticleSearch.Service.DimentionServices;
using ArticleSearch.Service.ProductFamilyDimensionMappingServices;
using ArticleSearch.Repositories;
using ArticleSearch.Data;

namespace ArticleSearch.Web.Controllers
{
    public class FamilyController : Controller
    {
        
        #region Declarations
        private readonly IProductFamilyService _productFamilyService;
        private readonly IDimentionService _dimentionService;
        private readonly IProductFamilyDimensionMappingService _productFamilyDimensionMappingService; 
        #endregion

        #region Ctor
		 public FamilyController(IUnitOfWork unitOfWork, IProductFamilyService productFamilyService, IDimentionService dimentionService, IProductFamilyDimensionMappingService productFamilyDimensionMappingService)
        {
            _dimentionService = dimentionService;
            _productFamilyService = productFamilyService;
            _productFamilyDimensionMappingService = productFamilyDimensionMappingService;
        }

 
	#endregion  

        #region Methods

         public ActionResult Create()
         {
             return View("Index");
         }

         [HttpPost]
         public ActionResult Create(FamilyInfoModel model)
         {
             if (ModelState.IsValid)
             {
                 var familyInfo = new ProductFamily
                 {
                     Id = model.Id,
                     DepartmentId = 1, //temprary take electricle Department
                     FamilyName = model.FamilyName,
                     FamilyNumber = model.FamilyNumber,
                     CategoryId = model.CategoryId,
                     Status = 0,
                     StandardReference = model.StandardReference,
                     CreatedBy = "", //for now we set it empty
                     CreatedDate = System.DateTime.Now
                 };
                 var familyId = _productFamilyService.InsertFamilies(familyInfo);
                 if (familyId == 0)
                 {
                     ViewBag.error = "family name or Number not Entered";
                     return View();
                 }

                 //dimension (the Dimension will be more, so need to create array and each dim store in table)
                 List<string> DimNames = new List<string>();
                 DimNames.Add("Dim_ Test 1");
                 DimNames.Add("Dim_ Test 2");
                 DimNames.Add("Dim_ Test 3");
                 DimNames.Add("Dim_ Test 4");
                 DimNames.Add("Dim_ Test 5");

                 model.DimensionName = DimNames;
                 foreach (var dim in model.DimensionName)
                 {
                     var count = 0;
                     var dims = new Dimension { Name = dim, Unit = "" };
                     var dimId = _dimentionService.InsertDimention(dims);
                     // inserting in mapping table
                     var familyDim_mapping = new ProductFamilyDimensionMapping { ProductFamilyId = familyId, DimensionId = Convert.ToInt16(dimId) };
                     if (_productFamilyDimensionMappingService.InsertProductFamilyDimensionMapping(familyDim_mapping))
                     {
                         count++;
                     }
                     if (count == model.DimensionName.Count)
                     {
                         ViewBag.success = "Family Inserted SuccessFully";
                     }
                 }
             }
             return View(model);
         }

         public ActionResult Demo()
         {
             return View();
         }
        [HttpPost]
         public ActionResult Demo(DemoModel demoModel)
         {
             var list = demoModel.Names;
             return View("Index");
         }

         #endregion
    }
}

ArticleSearch.Web/Views/Family/Demo.cshtml
@model ArticleSearch.Web.Models.DemoModel

@{
    ViewBag.Title = "Demo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Demo</h2>
@using (Html.BeginForm("Demo", "Family"))
{
    <label>Stuff</label>
    <div class="multi-field-wrapper">
      <div class="multi-fields">
        <div class="multi-field">
          <input type="text" name="Names" class="form-control">
          <button type="button" class="remove-field">Remove</button>
        </div>
      </div>
    <button type="button" class="add-field">Add field</button>
       
        <input type="submit" value="submit" />
  </div>
}
 

<script>
    $('.multi-field-wrapper').each(function () {
        var $wrapper = $('.multi-fields', this);
        $(".add-field", $(this)).click(function (e) {
            $('.multi-field:first-child', $wrapper).clone(true).appendTo($wrapper).find('input').val('').focus();
        });
        $('.multi-field .remove-field', $wrapper).click(function () {
            if ($('.multi-field', $wrapper).length > 1)
                $(this).parent('.multi-field').remove();
        });
    });
</script>

ArticleSearch.Web/Views/Family/Index.cshtml
@model ArticleSearch.Web.Models.FamilyInfoModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    
    <div id="main" class="col-sm-12">
        <div class="col-sm-6">
            <fieldset>
                <legend style="font-weight: bold">Create Family</legend>
                <div class="col-sm-10">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.FamilyNumber)
                    </div>
                </div>
                <div class="col-sm-10">
                    <div class="editor-label">
                        @Html.TextBoxFor(model => model.FamilyNumber, new { @class = "form-control", @type = "text", @id = "txtFamilyNo", @placeholder = "e.g. 0995 1500 00" })
                        @Html.ValidationMessageFor(model => model.FamilyNumber)
                    </div>
                </div>
                <div class="col-sm-10">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.FamilyName)
                    </div>
                </div>
                <div class="col-sm-10">
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.FamilyName, new { @class = "form-control", @type = "text", @id = "txtFamilyName", @placeholder = "e.g. Connector for printed boards" })
                        @Html.ValidationMessageFor(model => model.FamilyName)
                    </div>
                </div>
                <div class="col-sm-10">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.StandardReference)
                    </div>
                </div>
                <div class="col-sm-10">
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.StandardReference, new { @class = "form-control", @type = "text", @id = "txtStdRef", @placeholder = "e.g. abc" })
                        @Html.ValidationMessageFor(model => model.StandardReference)
                    </div>
                </div>
                <div class="col-sm-10">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.CategoryId)
                    </div>
                </div>
                <div class="col-sm-10">
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.CategoryId, new { @class = "form-control", @type = "text", @id = "txtCategory", @placeholder = "e.g. 3" })
                        @Html.ValidationMessageFor(model => model.CategoryId)
                    </div>
                </div>


                @*Dynamic fields Inputs textbox code*@
                <div class="col-sm-12">
                    <div class="editor-label">
                        @Html.LabelFor(model => model.DimensionName)
                    </div>
                </div>

                <div class="multi-field-wrapper ">
                    <div class="multi-fields">
                        <div class="multi-field ">
                            <div class="col-sm-10" style="margin-bottom:10px;">
                                <input type="text" name="DimName" placeholder="e.g. Voltage" class="form-control form-inline">
                            </div>
                            
                                <button type="button" class="remove-field" style="float:left;"><b>Remove</b></button>
                            
                        </div>
                    </div>
                    <div class="col-sm-12" style="margin:10px 0;">
                        <button type="button" class="add-field"><b>Add Field</b></button>
                    </div>
                </div>



                <div class="col-sm-8" style="margin-bottom:10px;">
                    <input type="submit" value="Create Family" class="btn first-bg-fifth-color btn-block" onclick="chekForBlank()" />
                </div>
            </fieldset>
        </div>
    </div>
      
    <span style="color: red">@ViewBag.error</span>
}


@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

<script>
    //dynamic fields functionality
    $('.multi-field-wrapper').each(function () {
        
        var $wrapper = $('.multi-fields', this);
        $(".add-field", $(this)).click(function (e) {
            // checking forexceeding limit of 30
            if ($('.multi-field', $wrapper).length >= 30) {
                alert('Dimension can not be More Than 30');
            } else {
                $('.multi-field:first-child', $wrapper).clone(true).appendTo($wrapper).find('input').val('').focus();
            }
           
            
        });
        $('.multi-field .remove-field', $wrapper).click(function () {
            if ($('.multi-field', $wrapper).length > 1) {
                $(this).parent('.multi-field').remove();
            }
            else {
                alert('atleast 1 field is Required'); 
            }
            
        });
    });
    // Validaitons
    function chekForBlank() {
        var familyNo = $('#ff').val();
        if (familyNo=="") {
            alert('Family Number is');
        }
    }
</script>